import unittest
from data_cleaning import clean_df
import pandas as pd
import json

with open ('06_text_df.json',encoding='utf-8') as f:
    data = json.load(f)

# writing the json data into a dataframe
df_json = pd.json_normalize(data, record_path =['PDF'])

class TestCleanData(unittest.TestCase):
    def test_clean_data(self):   
        end_result = clean_df(df_json)
    
        self.maxDiff = None  
        self.assertEqual(end_result['text_clean'].iloc[0][8],"EIXO RELAÇÕES DE TRABALHO Princípio 3: As empresas devem apoiar a liberdade de associação e o reconhecimento efetivo do direito à negociação coletiva * A Quinta da Estância apóia integralmente a liberdade de associação, inclusive participa ativamente de muitas associações patronais e outras instituições representativas. * Apoiamos também o direito a negociação coletiva, aplicando todas as deliberações cabíveis ao nosso segmento de negócio. Princípio 4: A eliminação de todas as formas de trabalho forçado e compulsório * A Quinta da Estância repudia qualquer forma de trabalho forçado e / ou compulsório. Não sendo tolerado este tipo de violação de tratados internacionais não só em nossas atividades diretas como em fornecedores, prestadores de serviço ou parceiros. Princípio 5: A abolição efetiva do trabalho infantil * Como trabalhamos com educação somos veementemente contra qualquer tipo de exploração infantil, estando aqui às relacionadas a questões psíquicas, morais ou físicas. Promovemos esta conscientização no restante de nossa cadeia, atingindo fornecedores, prestadores de serviço e parceiros. Princípio 6: A eliminação da discriminação com relação a emprego e profissão * A discriminação de qualquer tipo, gênero ou grau não possui espaço na Quinta da Estância Grande, pois promovemos a igualdade plena. Recebendo inclusive grupos portadores de necessidades especiais e realizando ações de capacitação e conscientização de colaboradores. Em caso de incidência de violações de questões relativas ao PRINCÍPIO DO TRABALHO a questão é imediatamente avaliada pela Diretoria, onde são determinadas medidas imediatas para retorno a normalidade e são deliberadas ações diretas cabíveis em cada caso.")
        self.assertEqual(end_result['text_clean'].iloc[576][0],"2012 中国华电集团公司 社会责任报告 2012 社会责任报告 发展 和谐共赢")
        self.assertEqual(end_result['text_clean'].iloc[15][0],"Vestas |Sustainability [URL] [DATE] PROFILE DISCOVER WIND PARTNERING SUSTAINABILITY FIND VESTAS TRACK RECORD POWERING SUSTAINABILITY COMMITMENTS SUSTAINABLE PRODUCTS MANAGING SUSTAINABILITY REPORTING Making wind work Together we power the future View Vestas' track record Our commitment to sustainability For more than 30 years our efforts have been devoted to raising the profile of wind as a mainstream energy source.")
        self.assertEqual(end_result['text_clean'].iloc[7][5],"6 o D'autre part, l'Ifop, par son activité d'études auprès des entreprises et organisations, ainsi que grâce au rayonnement de sa marque à laquelle sont associées des valeurs de fiabilité, de rigueur et de pertinence, contribue directement à la sensibilisation des grandes entreprises françaises aux enjeux du développement durable. En effet, l'Ifop poursuit chaque année depuis 2002 un Observatoire du Développement Durable. o Enfin, nous avons souhaité accentuer nos actions dans le domaine de l'environnement et construire notre stratégie d'entreprise en prenant en compte les différents facteurs liés au changement climatique et à l'augmentation inéluctable du prix des énergies fossiles. C'est pourquoi nous avons réalisé notre diagnostic Bilan Carbone® afin de sensibiliser le personnel aux enjeux et de mettre en place les actions qui nous permettrons de réduire notre empreinte carbone et par la même d'initier un processus vertueux. Principe n° 10 : Les entreprises sont invitées à agir contre la corruption sous toutes ses formes, y compris l'extorsion de fonds et les pots de vins L'Ifop est membre actif de la branche professionnelle Syntec (www.syntec.fr) et de l'association internationale Esomar (www.esomar.org), qui définissent et garantissent, aux niveaux national et international, l'ensemble des règles déontologiques de la profession, que l'Ifop s'engage donc, en tant que membre, à respecter et promouvoir. Depuis 2009, Olivier Bauby membre du Directoire, a été élu administrateur puis trésorier de la branche Etudes Marketing et Opinion de Syntec.")
        self.assertEqual(end_result['text_clean'].iloc[326][1],"")
        self.assertEqual(end_result['text_clean'].iloc[326][2],"")
        self.assertEqual(end_result['text_clean'].iloc[326][3],"")
        self.assertEqual(end_result['text_clean'].iloc[186][4],"5 ВОЛЯ сьогодні.2 Зміни за звітний період .2 Про звіт .3 Звернення Генерального директора компанії ВОЛЯ .4 Стейкхолдери ВОЛІ .7 Як вони дізнаються про розвиток компанії .7 Корпоративне управління .8 Боротьба з корупцією. Політика закупівель .8 Законодавча діяльність .8 Протидія піратству .9 Доступність інновацій .10 Революційне телебачення .10 Прорив на ринку В2В: «хмари» для малого та середнього бізнесу .11 ВОЛЯ розповідає про інновації професійній спільноті.11 ЗМІСТ")
        self.assertEqual(end_result['text_clean'].iloc[55][2],"3 3. Responsible business Practices 94 3.1. anti-corruption Procedures 94 3.2. Vnesh econom bank's cooperation with Stakeholders 99 3.3. client-centered Practices 102 4. corporate Life 107 4.1. hR Policies 107 4.2. environmental Initiatives 124 appendices 135 Table of Report compliance with GRI Guidelines and financial Service Sector Supplement 135 Statement of Progress in complying with the 10 Principles of Un Global compact 145 findings of non-financial audit of 2012 Veb Group Sustainability Report 146 contact Information 148")
        self.assertEqual(end_result['text_clean'].iloc[59][11],"34, rue de Laborde 75008 PARIS, FRANCE www.apsia.eu - tél :+33 1 44 69 02 03 S.A.S. au capital de 1000 000 € Siren 517 970 158 APE 7022 Watt Impact réduit l'impact du site web d'Apsia sur l'environnement En 2013, la consultation du site internet d'Apsia a engendré 20.249 Kwh d'électricité consommée, 100% étant issue d'une énergie renouvelable. Sans l'installation de Wattimpact. Apsia continue de sensibiliser ses consultants aux enjeux écologiques et conserve les bonnes initiatives adoptées auparavant à savoir : - Une utilisation restreinte de matériels jetables en plastique, l'utilisation de papiers recyclés pour les enveloppes, les cartes de visites - Un fournisseur local de papier recyclé afin de limiter l'émission de gaz à effet de serre - La signature de mail demeure dépourvue d'image et un rappel de l'engagement écologique d'Apsia en fin de signature")
        self.assertEqual(end_result['text_clean'].iloc[13][65],"GRI APPLICATION LEVEL APPROVAL AKKÖK SUSTAINABILITY REPORT 2012 64")
        self.assertEqual(end_result['text_clean'].iloc[22][1],"Reporte de Comunicación de Progreso del Pacto Global 2013 1 de marzo de 2014 Centro Médico Paitilla Página 2 Mensaje de Compromiso de la Dirección Ejecutiva 4 Filosofía Corporativa 5 Descripción de la Empresa 7 Nuestro Compromiso con los Principios del Pacto Global 8 DERECHOS HUMANOS: 8 Principio 1: Apoyar y respetar la protección de los derechos humanos reconocidos Internacionalmente dentro de su esfera de influencia. Principio 2: Asegurarse de no violar los derechos humanos. CONDICIONES LABORALES: 48 Principio 3: Apoyar la libertad de asociación y el reconocimiento efectivo del derecho a la Negociación Colectiva. Principio 4: Eliminación de todas las formas de trabajo forzoso y obligatorio. Principio 5: Abolición del trabajo infantil. Principio 6: Eliminación de la discriminación en relación con el empleo y la ocupación.")
        self.assertEqual(end_result['text_clean'].iloc[34][0],"Grant Thornton and the Unites Nations Global Compact Communication on Progress © 2014 Grant Thornton CJSC | Communication on Progress February 2014 Yerevan, Armenia")
        self.assertEqual(end_result['text_clean'].iloc[35][1],"2013 Unit\"edNations Global Compact .Compliance Report Jan 2014 + Ave. Conductores 505 + Col Constituyentes de Qro. 505, San Nicolás, N.L. 66493 MÉXICO + Tel + (52) 81*8*030*8000 + blopez@magnekon.com + www.magnekon.com+ www.viakon.com")
        self.assertEqual(end_result['text_clean'].iloc[43][10],'neunten Mal vergeben. Auch ikp Vorarlberg wurde Mitte Jänner rezertifiziert. "Wir leben Familie, privat wie beruflich. Die Familienfreundlichkeit ist bei uns im Leitbild verankert: Wir nehmen bei der Diensteinteilung auf den Stundenplan der Kinder, auf Arbeits- und Urlaubszeiten der Lebenspartnerinnen und Lebenspartner oder Kinderbetreuungszeiten Rücksicht. Die Auszeichnung freut mich doppelt: als Geschäftsführer und Familienvater", so Martin Dechant, Geschäftsführer ikp Vorarlberg GmbH. Ausschlaggebend für den Erhalt des Gütesiegels sind die familienfreundlichen Möglichkeiten, die das Unternehmen hat, sowie deren Umsetzung. Seite 11 von 23')
        self.assertEqual(end_result['text_clean'].iloc[635][0],"Greenstone Annual Communication on Progress February 2013 - February 2014")
        self.assertEqual(end_result['text_clean'].iloc[616][1],"Sommaire Déclaration de soutien continu d'Alexandre ARNON, associé fondateur de GBA & Associés .p 3 I- Principes relatifs aux Droits de l'Homme.p 4 Politique Mise en œuvre Mesures II- Principes relatifs aux conditions de travail.p 5 Politique Mise en œuvre Mesures III- Principes relatifs à l'environnement.p 7 Politique Mise en œuvre Mesures IV- Principes relatifs à la lutte contre la corruption.p 8 Politique Mise en œuvre Mesures 2")

if __name__ == '__main__':
    unittest.main()